image: "greyltc/archlinux"

before_script:
- pacman -Syu --noconfirm

  # Install dependencies through pacman
- pacman -S --noconfirm git base-devel pkg-config cmake

  # Install aurget
- git clone https://github.com/pbrisbin/aurget.git .aurget
- cp .aurget/aurget ./aurget
- rm -rf .aurget
- chmod a+x aurget

  # Install rustup and leap motion SDK
- yes no | ./aurget -S rustup-git leap-motion-sdk

  # Use rust nightly
- rustup default nightly

# Build and test the project
build:
  script:
  - rustc --version && cargo --version
  - cargo build --all --verbose
  - cargo test --all --verbose
