image: rust

stages:
  - lint
  - test

before_script:
  # Update and install dependencies
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends curl build-essential cmake pkg-config

  # Use Rust nightly
  - rustup default nightly
  - rustc --version && cargo --version

  # Install the Leap Motion SDK
  - ./ci/install_sdk

fmt:
  stage: lint
  before_script:
    # Install Rust nightly with rustfmt
    - rustup default nightly
    - rustup component add rustfmt-preview
    - rustc --version && cargo --version
  script:
    - cargo fmt --all -- --check

clippy:
  stage: lint
  before_script:
    # Install Rust nightly with clippy
    - rustup default nightly
    - rustup component add clippy-preview
    - rustc --version && cargo --version
  script:
    - cargo clippy --all -- --check

# Build and test the project
build:
  stage: test
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose
