image: rust

stages:
  - lint
  - build

before_script:
  # Update and install dependencies
  - apt-get update -yqq
  - apt-get install -yqq --no-install-recommends curl build-essential cmake pkg-config

  # Use Rust nightly
  - rustup default nightly
  - rustc --version && cargo --version

  # Install the Leap Motion SDK
  - ./ci/install_sdk

fmt:
  stage: lint
  before_script:
    # Install Rust nightly with rustfmt
    - rustup default nightly
    - rustup component add rustfmt-preview
    - rustc --version && cargo --version
  script:
    - cargo fmt --all -- --check

clippy:
  stage: lint
  script:
    - rustup component add clippy-preview
    - cargo clippy --all

# Build and test the project
build:
  stage: build
  artifacts:
    paths:
      - bin/*
    name: 'linux-dynamic'
    when: on_success
    expire_in: '1 month'
  script:
    - cargo build --all --verbose
    - cargo test --all --verbose
    - cargo build --all --verbose --release
    - mkdir -p ./bin
    - mv ./target/debug/cant-touch-this ./bin/cant-touch-this-debug
    - mv ./target/release/cant-touch-this ./bin/-cant-touch-this-release
