#!/bin/bash

set -e

echo "Starting LeapMotion SDK installation..."

# Determine the directory of this script
DIR=$( cd "$(dirname "$0")" ; pwd -P )

# Download Leap Motion SDK from self hosted server
echo "Downloading SDK files..."
mkdir -p /tmp/leap/
cd /tmp/leap
curl https://u.visee.me/dl/leap-motion/Leap_Motion_SDK_Linux_2.3.1.tgz -o /tmp/leap/LeapMotionSDK.tgz

# Extract the SDK, prepare the SDK directory
echo "Extracting SDK files..."
tar -zxf LeapMotionSDK.tgz
mv ./LeapDeveloperKit_2.3.1+31549_linux/LeapSDK ./LeapSDK
rm -rf ./LeapDeveloperKit_2.3.1+31549_linux/LeapSDK

# Install SDK library files on system for Linux or macOS
echo "Installing SDK files on system..."
if [[ $(uname) == "Linux" ]]; then
    echo "Installing SDK files for Linux..."
    cp ./LeapSDK/include/Leap*.h /usr/include/
    cp ./LeapSDK/lib/x64/libLeap.so /usr/lib/
    mkdir -p /usr/lib/pkgconfig
    cp $DIR/libleap.pc /usr/lib/pkgconfig/
elif [[ $(uname) == "Darwin" ]]; then
    echo "Installing SDK files for macOS..."
    cp ./LeapSDK/include/Leap*.h /usr/local/include/
    cp ./LeapSDK/lib/x64/libLeap.so /usr/local/lib/
    mkdir -p /usr/local/lib/pkgconfig
    cp $DIR/libleap.macOS.pc /usr/local/lib/pkgconfig/
else
    echo "Failed to install, unsupported system."
    exit 1
fi

# Remove the extracted SDK
echo "Remove temporary downloaded files..."
cd
rm -rf /tmp/leap

echo "Successfully installed Leap Motion SDK!"
